lib LibSdl3
  # extern SDL_DECLSPEC int SDLCALL SDL_GetNumLogicalCPUCores(void);
  fun get_num_logical_cpu_cores = SDL_GetNumLogicalCPUCores : Int
  # extern SDL_DECLSPEC int SDLCALL SDL_GetCPUCacheLineSize(void);
  fun getcpu_cache_line_size = SDL_GetCPUCacheLineSize : Int
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasAltiVec(void);
  fun has_alti_vec? = SDL_HasAltiVec : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasMMX(void);
  fun has_mmx? = SDL_HasMMX : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasSSE(void);
  fun ha_ssse? = SDL_HasSSE : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasSSE2(void);
  fun has_sse2? = SDL_HasSSE2 : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasSSE3(void);
  fun has_sse3? = SDL_HasSSE3 : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasSSE41(void);
  fun has_sse41? = SDL_HasSSE41 : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasSSE42(void);
  fun has_sse42? = SDL_HasSSE42 : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasAVX(void);
  fun has_avx? = SDL_HasAVX : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasAVX2(void);
  fun has_avx2? = SDL_HasAVX2 : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasAVX512F(void);
  fun has_avx512f? = SDL_HasAVX512F : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasARMSIMD(void);
  fun has_armsimd? = SDL_HasARMSIMD : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasNEON(void);
  fun has_neon? = SDL_HasNEON : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasLSX(void);
  fun has_lsx? = SDL_HasLSX : Bool
  # extern SDL_DECLSPEC bool SDLCALL SDL_HasLASX(void);
  fun has_lasx? = SDL_HasLASX : Bool
  # extern SDL_DECLSPEC int SDLCALL SDL_GetSystemRAM(void);
  fun get_system_ram = SDL_GetSystemRAM : Int
  # extern SDL_DECLSPEC size_t SDLCALL SDL_GetSIMDAlignment(void);
  fun get_simd_alignment = SDL_GetSIMDAlignment : LibC::SizeT
  # extern SDL_DECLSPEC int SDLCALL SDL_GetSystemPageSize(void);
  fun get_system_page_size = SDL_GetSystemPageSize : Int
end
